name: elderly_anti_fraud_app
description: A Flutter app to help elderly people prevent fraud.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1
  # State Management
  provider: ^6.1.2

  # HTTP requests
  http: ^1.2.1

  # Image picker
  image_picker: ^1.0.7

  # Speech to text
#  speech_to_text: ^6.5.0

  # WebView
  webview_flutter: ^4.0.0
  url_launcher: ^6.2.5

  # HTML rendering
  flutter_html: ^3.0.0-beta.2

  # Firebase
  firebase_core: ^2.32.0
  firebase_messaging: ^14.7.19
  cloud_firestore: ^4.15.8

  # UI components
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/