// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzmpn6Cil5yXEhu47cE39Ti_F9eSYP9mE',
    appId: '1:807060645872:web:5dd463c2b6c3067fa51f35',
    messagingSenderId: '807060645872',
    projectId: 'elderly-571a3',
    authDomain: 'elderly-571a3.firebaseapp.com',
    storageBucket: 'elderly-571a3.firebasestorage.app',
    measurementId: 'G-S3ND2978M8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqQ3c7ajlVgVP9ArqVPmpwfhczeK2jAok',
    appId: '1:807060645872:android:309a18a9e79ee6d9a51f35',
    messagingSenderId: '807060645872',
    projectId: 'elderly-571a3',
    storageBucket: 'elderly-571a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQdzAp1lzzOFvyYJmmYj-_eyBru3IvuS4',
    appId: '1:807060645872:ios:83b822ab214eae40a51f35',
    messagingSenderId: '807060645872',
    projectId: 'elderly-571a3',
    storageBucket: 'elderly-571a3.firebasestorage.app',
    iosBundleId: 'com.example.elderlyAntiFraudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQdzAp1lzzOFvyYJmmYj-_eyBru3IvuS4',
    appId: '1:807060645872:ios:83b822ab214eae40a51f35',
    messagingSenderId: '807060645872',
    projectId: 'elderly-571a3',
    storageBucket: 'elderly-571a3.firebasestorage.app',
    iosBundleId: 'com.example.elderlyAntiFraudApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzmpn6Cil5yXEhu47cE39Ti_F9eSYP9mE',
    appId: '1:807060645872:web:2419001b4c36f03da51f35',
    messagingSenderId: '807060645872',
    projectId: 'elderly-571a3',
    authDomain: 'elderly-571a3.firebaseapp.com',
    storageBucket: 'elderly-571a3.firebasestorage.app',
    measurementId: 'G-F3XYQHXSXT',
  );
}
